version: 0.2

phases:
  build:
    on-failure: ABORT
    commands:
      - cd ${CODEBUILD_SRC_DIR}
      - |-
        if [ ${ACTION} = "VALIDATE" ] ; then

          echo "==== Running: Terraform Validate ===="
          terraform init
          terraform validate

          echo "#TODO==== Running: TFLINT ===="
          #TODOtflint --init
          #TODOtflint

          echo "#TODO==== Running: Checkov ===="
          #TODOcheckov --framework terraform -d .

          echo "#TODO==== Running: TFSEC ===="
          #TODOtfsec .

        elif [ ${ACTION} = "PLAN" ] ; then

          echo "==== Running: Terraform Plan ===="
          terraform init
          terraform plan -out=tfplan -input=false -no-color
          terraform show -json tfplan > tfplan.json

          echo "#TODO==== Running: OPA ===="
          #TODOOPA_CHECK=$(opa exec --decision terraform/analysis/authz -b policy/ tfplan.json | jq -r ".result[] |.result")
          #TODOecho "OPA Evaluation Check = $OPA_CHECK"
          #TODOif ! $OPA_CHECK; then
          #TODO  printf '%s\n' "OPA evaluation failed" >&2
          #TODO  exit 1
          #TODOfi

        elif [ ${ACTION} = "APPLY" ] ; then

          echo "==== Running: Terraform Apply ===="
          terraform init
          terraform apply -no-color -auto-approve tfplan

        elif [ ${ACTION} = "DESTROY" ] ; then

          echo "==== Running: Terraform Destroy ===="
          terraform init
          terraform destroy -no-color -auto-approve
        fi

artifacts:
  files:
    - '**/*'
